version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-soucer
    ports:
      - 8080:80
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
